[2024-10-15T15:17:53.159+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T15:17:53.179+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: main_v07.extract manual__2024-10-15T15:17:52.386396+00:00 [queued]>
[2024-10-15T15:17:53.187+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: main_v07.extract manual__2024-10-15T15:17:52.386396+00:00 [queued]>
[2024-10-15T15:17:53.188+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 6
[2024-10-15T15:17:53.310+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): extract> on 2024-10-15 15:17:52.386396+00:00
[2024-10-15T15:17:53.316+0000] {standard_task_runner.py:72} INFO - Started process 233 to run task
[2024-10-15T15:17:53.321+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'main_v07', 'extract', 'manual__2024-10-15T15:17:52.386396+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp_c6ut9wk']
[2024-10-15T15:17:53.325+0000] {standard_task_runner.py:105} INFO - Job 50: Subtask extract
[2024-10-15T15:17:53.375+0000] {task_command.py:467} INFO - Running <TaskInstance: main_v07.extract manual__2024-10-15T15:17:52.386396+00:00 [running]> on host aa41fc5ff3d5
[2024-10-15T15:17:53.439+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='main_v07' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T15:17:52.386396+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T15:17:52.386396+00:00'
[2024-10-15T15:17:53.440+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T15:18:04.665+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/extract/extract.py", line 58, in extract_data
    merged_dataset.toPandas().to_csv("/opt/airflow/data/processed", sep=',',header=True,index=F)
NameError: name 'F' is not defined
[2024-10-15T15:18:04.680+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=main_v07, task_id=extract, run_id=manual__2024-10-15T15:17:52.386396+00:00, execution_date=20241015T151752, start_date=20241015T151753, end_date=20241015T151804
[2024-10-15T15:18:04.700+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T15:18:04.701+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 50 for task extract (name 'F' is not defined; 233)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/opt/airflow/scripts/extract/extract.py", line 58, in extract_data
    merged_dataset.toPandas().to_csv("/opt/airflow/data/processed", sep=',',header=True,index=F)
NameError: name 'F' is not defined
[2024-10-15T15:18:04.743+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-15T15:18:04.778+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T15:18:04.779+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
